// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use super::OracleCase;

macro_rules! case {
    ($id:literal, $feature:literal, $sql:literal) => {
        OracleCase {
            id: $id,
            feature: $feature,
            sql: $sql,
        }
    };
}

pub const STATEMENT_CASES: &[OracleCase] = &[
    case!("admin.keys", "ADMINISTER KEY MANAGEMENT", "ADMINISTER KEY MANAGEMENT CREATE KEYSTORE '/var/lib/oracle/keystore' IDENTIFIED BY password"),
    case!("alter.analytic_view", "ALTER ANALYTIC VIEW", "ALTER ANALYTIC VIEW sales_av COMPILE"),
    case!("alter.assertion", "ALTER ASSERTION", "ALTER ASSERTION positive_salary ENABLE VALIDATE"),
    case!("alter.attribute_dimension", "ALTER ATTRIBUTE DIMENSION", "ALTER ATTRIBUTE DIMENSION time_attr_dim COMPILE"),
    case!("alter.audit_policy", "ALTER AUDIT POLICY", "ALTER AUDIT POLICY app_audit ADD ACTIONS SELECT ON hr.employees"),
    case!("alter.cluster", "ALTER CLUSTER", "ALTER CLUSTER employee_cluster SIZE 1024"),
    case!("alter.database", "ALTER DATABASE", "ALTER DATABASE FORCE LOGGING"),
    case!("alter.database_dictionary", "ALTER DATABASE DICTIONARY", "ALTER DATABASE DICTIONARY ENCRYPT CREDENTIALS"),
    case!("alter.dimension", "ALTER DIMENSION", "ALTER DIMENSION products_dim COMPILE"),
    case!("alter.directive", "ALTER DIRECTIVE (VALIDATE)", "ALTER DIRECTIVE validate_email ENABLE"),
    case!("alter.diskgroup", "ALTER DISKGROUP", "ALTER DISKGROUP data CHECK ALL"),
    case!("alter.domain", "ALTER DOMAIN", "ALTER DOMAIN email_domain ADD DISPLAY email_value"),
    case!("alter.end_user", "ALTER END USER", "ALTER END USER app_customer ACCOUNT UNLOCK"),
    case!("alter.flashback_archive", "ALTER FLASHBACK ARCHIVE", "ALTER FLASHBACK ARCHIVE history_archive MODIFY RETENTION 5 YEAR"),
    case!("alter.hierarchy", "ALTER HIERARCHY", "ALTER HIERARCHY time_hierarchy COMPILE"),
    case!("alter.indextype", "ALTER INDEXTYPE", "ALTER INDEXTYPE text_index_type COMPILE"),
    case!("alter.inmemory_join_group", "ALTER INMEMORY JOIN GROUP", "ALTER INMEMORY JOIN GROUP sales_join_group ADD (sales (customer_id))"),
    case!("alter.java", "ALTER JAVA", "ALTER JAVA SOURCE \"Example\" COMPILE"),
    case!("alter.duality_view", "ALTER JSON RELATIONAL DUALITY VIEW", "ALTER JSON RELATIONAL DUALITY VIEW orders_dv ENABLE LOGICAL REPLICATION"),
    case!("alter.lockdown_profile", "ALTER LOCKDOWN PROFILE", "ALTER LOCKDOWN PROFILE app_lockdown DISABLE STATEMENT = ('ALTER SYSTEM')"),
    case!("alter.mv_log", "ALTER MATERIALIZED VIEW LOG", "ALTER MATERIALIZED VIEW LOG ON employees ADD (salary)"),
    case!("alter.zonemap", "ALTER MATERIALIZED ZONEMAP", "ALTER MATERIALIZED ZONEMAP sales_zm REBUILD"),
    case!("alter.mle_env", "ALTER MLE ENV", "ALTER MLE ENV app_env COMPILE"),
    case!("alter.mle_module", "ALTER MLE MODULE", "ALTER MLE MODULE app_module SET METADATA USING CLOB '{\"name\":\"app\"}'"),
    case!("alter.operator", "ALTER OPERATOR", "ALTER OPERATOR contains_text COMPILE"),
    case!("alter.outline", "ALTER OUTLINE", "ALTER OUTLINE report_outline ENABLE"),
    case!("alter.pdb", "ALTER PLUGGABLE DATABASE", "ALTER PLUGGABLE DATABASE apppdb OPEN READ WRITE"),
    case!("alter.pmem", "ALTER PMEM FILESTORE", "ALTER PMEM FILESTORE app_pmem RESIZE 4G"),
    case!("alter.profile", "ALTER PROFILE", "ALTER PROFILE app_profile LIMIT FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LIFE_TIME 90"),
    case!("alter.property_graph", "ALTER PROPERTY GRAPH", "ALTER PROPERTY GRAPH social_graph COMPILE"),
    case!("alter.resource_cost", "ALTER RESOURCE COST", "ALTER RESOURCE COST CPU_PER_SESSION 1000 CONNECT_TIME 10"),
    case!("alter.role", "ALTER ROLE", "ALTER ROLE app_role NOT IDENTIFIED"),
    case!("alter.rollback_segment", "ALTER ROLLBACK SEGMENT", "ALTER ROLLBACK SEGMENT rb_app ONLINE"),
    case!("alter.session", "ALTER SESSION", "ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD'"),
    case!("alter.system", "ALTER SYSTEM", "ALTER SYSTEM SET open_cursors = 500 SCOPE = BOTH"),
    case!("alter.tablespace", "ALTER TABLESPACE", "ALTER TABLESPACE app_data READ ONLY"),
    case!("alter.tablespace_set", "ALTER TABLESPACE SET", "ALTER TABLESPACE SET app_ts_set READ ONLY"),
    case!("alter.user", "ALTER USER", "ALTER USER app_user QUOTA UNLIMITED ON app_data ACCOUNT UNLOCK"),
    case!("analyze.table", "ANALYZE", "ANALYZE TABLE employees VALIDATE STRUCTURE CASCADE"),
    case!("statistics.associate", "ASSOCIATE STATISTICS", "ASSOCIATE STATISTICS WITH COLUMNS employees.salary USING salary_stats_type"),
    case!("audit.unified", "AUDIT (Unified Auditing)", "AUDIT POLICY app_audit BY app_user WHENEVER SUCCESSFUL"),
    case!("create.analytic_view", "CREATE ANALYTIC VIEW", "CREATE ANALYTIC VIEW sales_av USING sales DIMENSION BY (time_attr_dim KEY month REFERENCES month) MEASURES (sales_amount FACT sales.amount)"),
    case!("create.application_identity", "CREATE APPLICATION IDENTITY", "CREATE APPLICATION IDENTITY app_identity MAPPED TO 'application-client'"),
    case!("create.assertion", "CREATE ASSERTION", "CREATE ASSERTION employees_exist CHECK (EXISTS (SELECT 1 FROM employees))"),
    case!("create.attribute_dimension", "CREATE ATTRIBUTE DIMENSION", "CREATE ATTRIBUTE DIMENSION time_attr_dim USING calendar ATTRIBUTES (year, month) LEVEL year KEY year LEVEL month KEY month DETERMINES (year)"),
    case!("create.audit_policy", "CREATE AUDIT POLICY", "CREATE AUDIT POLICY app_audit ACTIONS SELECT, INSERT, UPDATE ON hr.employees"),
    case!("create.cluster", "CREATE CLUSTER", "CREATE CLUSTER employee_cluster (department_id NUMBER) SIZE 1024"),
    case!("create.context", "CREATE CONTEXT", "CREATE CONTEXT app_context USING app_context_pkg ACCESSED GLOBALLY"),
    case!("create.controlfile", "CREATE CONTROLFILE", "CREATE CONTROLFILE SET DATABASE appdb RESETLOGS NOARCHIVELOG"),
    case!("create.data_grant", "CREATE DATA GRANT", "CREATE DATA GRANT active_employees AS SELECT ON hr.employees WHERE active = TRUE TO app_role"),
    case!("create.data_role", "CREATE DATA ROLE", "CREATE DATA ROLE app_data_role LOCAL"),
    case!("create.database", "CREATE DATABASE", "CREATE DATABASE appdb USER SYS IDENTIFIED BY password USER SYSTEM IDENTIFIED BY password CHARACTER SET AL32UTF8"),
    case!("create.dimension", "CREATE DIMENSION", "CREATE DIMENSION products_dim LEVEL product IS products.product_id LEVEL category IS products.category_id HIERARCHY product_rollup (product CHILD OF category)"),
    case!("create.directive", "CREATE DIRECTIVE (VALIDATE)", "CREATE DIRECTIVE validate_email AS VALIDATE email_address USING email_domain"),
    case!("create.diskgroup", "CREATE DISKGROUP", "CREATE DISKGROUP data NORMAL REDUNDANCY DISK '/dev/oracleasm/disks/DATA1'"),
    case!("create.domain", "CREATE DOMAIN", "CREATE DOMAIN positive_number AS NUMBER CONSTRAINT positive_number_ck CHECK (positive_number > 0)"),
    case!("create.edition", "CREATE EDITION", "CREATE EDITION app_v2 AS CHILD OF ora$base"),
    case!("create.end_user", "CREATE END USER", "CREATE END USER app_customer IDENTIFIED BY password ACCOUNT UNLOCK"),
    case!("create.end_user_context", "CREATE END USER CONTEXT", "CREATE END USER CONTEXT customer_context USING customer_context_pkg"),
    case!("create.flashback_archive", "CREATE FLASHBACK ARCHIVE", "CREATE FLASHBACK ARCHIVE history_archive TABLESPACE app_data RETENTION 5 YEAR"),
    case!("create.flexible_domain", "CREATE FLEXIBLE DOMAIN", "CREATE FLEXIBLE DOMAIN order_value (amount AS NUMBER, currency AS VARCHAR2(3)) CHOOSE DOMAIN USING (CASE currency WHEN 'USD' THEN amount END)"),
    case!("create.hierarchy", "CREATE HIERARCHY", "CREATE HIERARCHY time_hierarchy USING time_attr_dim (month CHILD OF year)"),
    case!("create.hybrid_vector_index", "CREATE HYBRID VECTOR INDEX", "CREATE HYBRID VECTOR INDEX documents_hybrid_ix ON documents (body) PARAMETERS ('MODEL all_minilm_l6_v2')"),
    case!("create.iceberg_table", "CREATE ICEBERG TABLE", "CREATE ICEBERG TABLE app.sales_catalog WITH CATALOG app_catalog"),
    case!("create.indextype", "CREATE INDEXTYPE", "CREATE INDEXTYPE text_index_type FOR contains_text(VARCHAR2, VARCHAR2) USING text_index_impl_t"),
    case!("create.inmemory_join_group", "CREATE INMEMORY JOIN GROUP", "CREATE INMEMORY JOIN GROUP sales_join_group (sales(customer_id), customers(customer_id))"),
    case!("create.java", "CREATE JAVA", "CREATE OR REPLACE AND COMPILE JAVA SOURCE NAMED \"Example\" AS public class Example { public static int twice(int n) { return n * 2; } }"),
    case!("create.duality_view", "CREATE JSON RELATIONAL DUALITY VIEW", "CREATE JSON RELATIONAL DUALITY VIEW orders_dv AS SELECT JSON {'_id' : o.order_id, 'status' : o.status} FROM orders o"),
    case!("create.lockdown_profile", "CREATE LOCKDOWN PROFILE", "CREATE LOCKDOWN PROFILE app_lockdown"),
    case!("create.logical_partition_tracking", "CREATE LOGICAL PARTITION TRACKING", "CREATE LOGICAL PARTITION TRACKING ON sales PARTITION BY RANGE (sold_on) (PARTITION p2026 VALUES LESS THAN (DATE '2027-01-01'))"),
    case!("create.zonemap", "CREATE MATERIALIZED ZONEMAP", "CREATE MATERIALIZED ZONEMAP sales_zm ON sales (sold_on, amount)"),
    case!("create.mle_env", "CREATE MLE ENV", "CREATE MLE ENV app_env LANGUAGE OPTIONS '{\"js.strict\":true}'"),
    case!("create.mle_module", "CREATE MLE MODULE", "CREATE MLE MODULE app_module LANGUAGE JAVASCRIPT AS 'export function twice(n) { return n * 2; }'"),
    case!("create.multi_column_domain", "CREATE MULTI COLUMN DOMAIN", "CREATE DOMAIN money_domain AS (amount AS NUMBER, currency AS VARCHAR2(3))"),
    case!("create.operator", "CREATE OPERATOR", "CREATE OPERATOR contains_text BINDING (VARCHAR2, VARCHAR2) RETURN NUMBER USING contains_text_impl"),
    case!("create.outline", "CREATE OUTLINE", "CREATE OUTLINE report_outline ON SELECT * FROM employees"),
    case!("create.pfile", "CREATE PFILE", "CREATE PFILE = '/tmp/initapp.ora' FROM MEMORY"),
    case!("create.pdb", "CREATE PLUGGABLE DATABASE", "CREATE PLUGGABLE DATABASE apppdb ADMIN USER pdb_admin IDENTIFIED BY password"),
    case!("create.pmem", "CREATE PMEM FILESTORE", "CREATE PMEM FILESTORE app_pmem MOUNTPOINT '/pmem/app' SIZE 4G"),
    case!("create.profile", "CREATE PROFILE", "CREATE PROFILE app_profile LIMIT SESSIONS_PER_USER 10 FAILED_LOGIN_ATTEMPTS 5"),
    case!("create.property_graph", "CREATE PROPERTY GRAPH", "CREATE PROPERTY GRAPH social_graph VERTEX TABLES (persons KEY (person_id)) EDGE TABLES (follows KEY (follow_id) SOURCE KEY (from_id) REFERENCES persons(person_id) DESTINATION KEY (to_id) REFERENCES persons(person_id))"),
    case!("create.restore_point", "CREATE RESTORE POINT", "CREATE RESTORE POINT before_upgrade GUARANTEE FLASHBACK DATABASE"),
    case!("create.role", "CREATE ROLE", "CREATE ROLE app_role NOT IDENTIFIED"),
    case!("create.rollback_segment", "CREATE ROLLBACK SEGMENT", "CREATE ROLLBACK SEGMENT rb_app TABLESPACE app_data"),
    case!("create.schema", "CREATE SCHEMA", "CREATE SCHEMA AUTHORIZATION app_user CREATE TABLE settings (name VARCHAR2(100), value VARCHAR2(100))"),
    case!("create.single_column_domain", "CREATE SINGLE COLUMN DOMAIN", "CREATE DOMAIN email_domain AS VARCHAR2(320) CONSTRAINT email_ck CHECK (REGEXP_LIKE(email_domain, '.+@.+'))"),
    case!("create.spfile", "CREATE SPFILE", "CREATE SPFILE = '/tmp/spfileapp.ora' FROM MEMORY"),
    case!("create.tablespace", "CREATE TABLESPACE", "CREATE TABLESPACE app_data DATAFILE '/tmp/app_data.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M"),
    case!("create.tablespace_set", "CREATE TABLESPACE SET", "CREATE TABLESPACE SET app_ts_set USING TEMPLATE (DATAFILE SIZE 100M)"),
    case!("create.user", "CREATE USER", "CREATE USER app_user IDENTIFIED BY password DEFAULT TABLESPACE app_data QUOTA 100M ON app_data"),
    case!("statistics.disassociate", "DISASSOCIATE STATISTICS", "DISASSOCIATE STATISTICS FROM COLUMNS employees.salary FORCE"),
    case!("drop.analytic_view", "DROP ANALYTIC VIEW", "DROP ANALYTIC VIEW sales_av"),
    case!("drop.application_identity", "DROP APPLICATION IDENTITY", "DROP APPLICATION IDENTITY app_identity"),
    case!("drop.assertion", "DROP ASSERTION", "DROP ASSERTION employees_exist"),
    case!("drop.attribute_dimension", "DROP ATTRIBUTE DIMENSION", "DROP ATTRIBUTE DIMENSION time_attr_dim"),
    case!("drop.audit_policy", "DROP AUDIT POLICY", "DROP AUDIT POLICY app_audit"),
    case!("drop.cluster", "DROP CLUSTER", "DROP CLUSTER employee_cluster INCLUDING TABLES CASCADE CONSTRAINTS"),
    case!("drop.context", "DROP CONTEXT", "DROP CONTEXT app_context"),
    case!("drop.data_grant", "DROP DATA GRANT", "DROP DATA GRANT app.active_employees"),
    case!("drop.data_role", "DROP DATA ROLE", "DROP DATA ROLE app_data_role"),
    case!("drop.database", "DROP DATABASE", "DROP DATABASE"),
    case!("drop.dimension", "DROP DIMENSION", "DROP DIMENSION products_dim"),
    case!("drop.directive", "DROP DIRECTIVE (VALIDATE)", "DROP DIRECTIVE validate_email"),
    case!("drop.diskgroup", "DROP DISKGROUP", "DROP DISKGROUP data EXCLUDING CONTENTS"),
    case!("drop.domain", "DROP DOMAIN", "DROP DOMAIN email_domain FORCE PRESERVE"),
    case!("drop.edition", "DROP EDITION", "DROP EDITION app_v2 CASCADE"),
    case!("drop.end_user", "DROP END USER", "DROP END USER app_customer"),
    case!("drop.flashback_archive", "DROP FLASHBACK ARCHIVE", "DROP FLASHBACK ARCHIVE history_archive"),
    case!("drop.hierarchy", "DROP HIERARCHY", "DROP HIERARCHY time_hierarchy"),
    case!("drop.iceberg_table", "DROP ICEBERG TABLE", "DROP ICEBERG TABLE app.sales_catalog WITHIN CATALOG app_catalog PURGE"),
    case!("drop.indextype", "DROP INDEXTYPE", "DROP INDEXTYPE text_index_type FORCE"),
    case!("drop.inmemory_join_group", "DROP INMEMORY JOIN GROUP", "DROP INMEMORY JOIN GROUP sales_join_group"),
    case!("drop.java", "DROP JAVA", "DROP JAVA SOURCE \"Example\""),
    case!("drop.lockdown_profile", "DROP LOCKDOWN PROFILE", "DROP LOCKDOWN PROFILE app_lockdown"),
    case!("drop.mv_log", "DROP MATERIALIZED VIEW LOG", "DROP MATERIALIZED VIEW LOG ON employees"),
    case!("drop.zonemap", "DROP MATERIALIZED ZONEMAP", "DROP MATERIALIZED ZONEMAP sales_zm"),
    case!("drop.mle_env", "DROP MLE ENV", "DROP MLE ENV app_env"),
    case!("drop.mle_module", "DROP MLE MODULE", "DROP MLE MODULE app_module"),
    case!("drop.operator", "DROP OPERATOR", "DROP OPERATOR contains_text FORCE"),
    case!("drop.outline", "DROP OUTLINE", "DROP OUTLINE report_outline"),
    case!("drop.pdb", "DROP PLUGGABLE DATABASE", "DROP PLUGGABLE DATABASE apppdb INCLUDING DATAFILES"),
    case!("drop.pmem", "DROP PMEM FILESTORE", "DROP PMEM FILESTORE app_pmem EXCLUDING CONTENTS"),
    case!("drop.profile", "DROP PROFILE", "DROP PROFILE app_profile CASCADE"),
    case!("drop.property_graph", "DROP PROPERTY GRAPH", "DROP PROPERTY GRAPH social_graph"),
    case!("drop.restore_point", "DROP RESTORE POINT", "DROP RESTORE POINT before_upgrade"),
    case!("drop.role", "DROP ROLE", "DROP ROLE app_role"),
    case!("drop.rollback_segment", "DROP ROLLBACK SEGMENT", "DROP ROLLBACK SEGMENT rb_app"),
    case!("drop.tablespace", "DROP TABLESPACE", "DROP TABLESPACE app_data INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS"),
    case!("drop.tablespace_set", "DROP TABLESPACE SET", "DROP TABLESPACE SET app_ts_set INCLUDING CONTENTS AND DATAFILES"),
    case!("drop.user", "DROP USER", "DROP USER app_user CASCADE"),
    case!("flashback.database", "FLASHBACK DATABASE", "FLASHBACK DATABASE TO RESTORE POINT before_upgrade"),
    case!("flashback.table", "FLASHBACK TABLE", "FLASHBACK TABLE employees TO TIMESTAMP SYSTIMESTAMP - INTERVAL '1' HOUR ENABLE TRIGGERS"),
    case!("grant.data_role", "GRANT DATA ROLE", "GRANT DATA ROLE app_data_role TO app_user"),
    case!("noaudit.traditional", "NOAUDIT (Traditional Auditing)", "NOAUDIT SELECT TABLE BY app_user WHENEVER SUCCESSFUL"),
    case!("noaudit.unified", "NOAUDIT (Unified Auditing)", "NOAUDIT POLICY app_audit BY app_user"),
    case!("purge.recyclebin", "PURGE", "PURGE RECYCLEBIN"),
    case!("revoke.data_role", "REVOKE DATA ROLE", "REVOKE DATA ROLE app_data_role FROM app_user"),
    case!("set.data_grants", "SET USE DATA GRANTS ONLY", "SET USE DATA GRANTS ONLY ON hr.employees ENABLED"),
    case!("truncate.cluster", "TRUNCATE CLUSTER", "TRUNCATE CLUSTER employee_cluster DROP STORAGE"),
    case!("drop.cluster.plain", "DROP CLUSTER", "DROP CLUSTER employee_cluster"),
    case!("drop.diskgroup.plain", "DROP DISKGROUP", "DROP DISKGROUP data"),
    case!("drop.domain.force", "DROP DOMAIN", "DROP DOMAIN email_domain FORCE"),
    case!("drop.edition.plain", "DROP EDITION", "DROP EDITION app_v2"),
    case!("drop.iceberg_table.catalog", "DROP ICEBERG TABLE", "DROP ICEBERG TABLE app.sales_catalog WITHIN CATALOG app_catalog"),
    case!("drop.indextype.plain", "DROP INDEXTYPE", "DROP INDEXTYPE text_index_type"),
    case!("drop.pdb.plain", "DROP PLUGGABLE DATABASE", "DROP PLUGGABLE DATABASE apppdb"),
    case!("drop.profile.plain", "DROP PROFILE", "DROP PROFILE app_profile"),
    case!("drop.tablespace.plain", "DROP TABLESPACE", "DROP TABLESPACE app_data"),
    case!("drop.user.plain", "DROP USER", "DROP USER app_user"),
    case!("drop.user.if_exists", "DROP USER", "DROP USER IF EXISTS app_user CASCADE"),
    case!("drop.data_role.if_exists", "DROP DATA ROLE", "DROP DATA ROLE IF EXISTS app_data_role"),
    case!("drop.mv_log.if_exists", "DROP MATERIALIZED VIEW LOG", "DROP MATERIALIZED VIEW LOG IF EXISTS ON employees"),
];
